[2022-07-10 12:45:02,093] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-07-09T00:00:00+00:00 [queued]>
[2022-07-10 12:45:02,106] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-07-09T00:00:00+00:00 [queued]>
[2022-07-10 12:45:02,107] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-10 12:45:02,107] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-10 12:45:02,107] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-10 12:45:02,120] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-09 00:00:00+00:00
[2022-07-10 12:45:02,124] {standard_task_runner.py:52} INFO - Started process 83 to run task
[2022-07-10 12:45:02,127] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-07-09T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmprjl9zt2v', '--error-file', '/tmp/tmpvhhoqxi_']
[2022-07-10 12:45:02,127] {standard_task_runner.py:80} INFO - Job 62: Subtask inaccurate
[2022-07-10 12:45:02,176] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-07-09T00:00:00+00:00 [running]> on host 18ea9465fe18
[2022-07-10 12:45:02,225] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-09T00:00:00+00:00
[2022-07-10 12:45:02,226] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-10 12:45:02,226] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo  'inaccurate' "]
[2022-07-10 12:45:02,234] {subprocess.py:85} INFO - Output:
[2022-07-10 12:45:02,236] {subprocess.py:89} INFO - inaccurate
[2022-07-10 12:45:02,236] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-10 12:45:02,258] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220709T000000, start_date=20220710T124502, end_date=20220710T124502
[2022-07-10 12:45:02,298] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-10 12:45:02,322] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
