[2022-07-11 08:34:42,419] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-07-10T00:00:00+00:00 [queued]>
[2022-07-11 08:34:42,426] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-07-10T00:00:00+00:00 [queued]>
[2022-07-11 08:34:42,426] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-11 08:34:42,426] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-11 08:34:42,426] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-11 08:34:42,433] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-10 00:00:00+00:00
[2022-07-11 08:34:42,437] {standard_task_runner.py:52} INFO - Started process 3790 to run task
[2022-07-11 08:34:42,439] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-07-10T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmp1jyjw7gt', '--error-file', '/tmp/tmp3xuq9vab']
[2022-07-11 08:34:42,439] {standard_task_runner.py:80} INFO - Job 44: Subtask inaccurate
[2022-07-11 08:34:42,468] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-07-10T00:00:00+00:00 [running]> on host 1f92e2add508
[2022-07-11 08:34:42,498] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-10T00:00:00+00:00
[2022-07-11 08:34:42,499] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-11 08:34:42,499] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo  'inaccurate' "]
[2022-07-11 08:34:42,507] {subprocess.py:85} INFO - Output:
[2022-07-11 08:34:42,508] {subprocess.py:89} INFO - inaccurate
[2022-07-11 08:34:42,508] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-11 08:34:42,525] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220710T000000, start_date=20220711T083442, end_date=20220711T083442
[2022-07-11 08:34:42,571] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-11 08:34:42,592] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
