[2022-07-04 05:34:58,718] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-07-04T05:34:55.619101+00:00 [queued]>
[2022-07-04 05:34:58,725] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-07-04T05:34:55.619101+00:00 [queued]>
[2022-07-04 05:34:58,726] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 05:34:58,726] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-04 05:34:58,726] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 05:34:58,732] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-04 05:34:55.619101+00:00
[2022-07-04 05:34:58,735] {standard_task_runner.py:52} INFO - Started process 2123 to run task
[2022-07-04 05:34:58,737] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2022-07-04T05:34:55.619101+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmpr5wee5b3', '--error-file', '/tmp/tmpl2_tf026']
[2022-07-04 05:34:58,737] {standard_task_runner.py:80} INFO - Job 445: Subtask inaccurate
[2022-07-04 05:34:58,777] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate manual__2022-07-04T05:34:55.619101+00:00 [running]> on host 1936d03cc531
[2022-07-04 05:34:58,809] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T05:34:55.619101+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T05:34:55.619101+00:00
[2022-07-04 05:34:58,809] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-04 05:34:58,810] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo  'inaccurate' "]
[2022-07-04 05:34:58,817] {subprocess.py:85} INFO - Output:
[2022-07-04 05:34:58,818] {subprocess.py:89} INFO - inaccurate
[2022-07-04 05:34:58,818] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-04 05:34:58,836] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220704T053455, start_date=20220704T053458, end_date=20220704T053458
[2022-07-04 05:34:58,869] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-04 05:34:58,910] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
