[2022-07-11 08:50:26,812] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-07-11T08:50:23.490084+00:00 [queued]>
[2022-07-11 08:50:26,821] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-07-11T08:50:23.490084+00:00 [queued]>
[2022-07-11 08:50:26,821] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-11 08:50:26,821] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-11 08:50:26,821] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-11 08:50:26,831] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-11 08:50:23.490084+00:00
[2022-07-11 08:50:26,835] {standard_task_runner.py:52} INFO - Started process 4546 to run task
[2022-07-11 08:50:26,837] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2022-07-11T08:50:23.490084+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmpjpcajo7x', '--error-file', '/tmp/tmpe5q7s_bz']
[2022-07-11 08:50:26,838] {standard_task_runner.py:80} INFO - Job 54: Subtask inaccurate
[2022-07-11 08:50:26,878] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate manual__2022-07-11T08:50:23.490084+00:00 [running]> on host 1f92e2add508
[2022-07-11 08:50:26,916] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-11T08:50:23.490084+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-11T08:50:23.490084+00:00
[2022-07-11 08:50:26,916] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-11 08:50:26,917] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo  'inaccurate' "]
[2022-07-11 08:50:26,926] {subprocess.py:85} INFO - Output:
[2022-07-11 08:50:26,928] {subprocess.py:89} INFO - inaccurate
[2022-07-11 08:50:26,928] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-11 08:50:26,945] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220711T085023, start_date=20220711T085026, end_date=20220711T085026
[2022-07-11 08:50:26,970] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-11 08:50:26,990] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
